export const FETCH_MESSAGES = 'FETCH_MESSAGES'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'
export const LIKE_MESSAGE = 'LIKE_MESSAGE'
export const TAKE_ALL_MESSAGES = 'TAKE_ALL_MESSAGES'

